site_name: Acquia BLT Documentaton

repo_url: https://github.com/acquia/blt
site_description: 'BLT - Acquia Build & Launch Tools'
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Home: 'index.md'
  - Overview: 'README.md'
  - Getting started:
    - Installation & upgrade:  'INSTALL.md'
    - Local development: 'docs/local-development.md'
  - Project documentation:
    - Overview: 'template/README.md'
    - Developer:
          - Onboarding: 'docs/onboarding.md'
          - Repository architecture: 'docs/repo-architecture.md'
          - Running project tasks:
            - Overview: 'docs/project-tasks.md'
            - Patches: 'template/patches/README.md'
            - Drush: 'template/drush/README.md'
            - Git hooks: 'template/scripts/git-hooks/README.md'
          - Best practices:
            - Overview: 'docs/best-practices.md'
            - Views: 'docs/views.md'
          - Workflow: 'docs/dev-workflow.md'
          - Automated testing: 'template/tests/README.md'
    - Technical Architect:
        - Project architecture document: 'docs/architecture.md'
        - Deploying to cloud: 'docs/deploy.md'
        - Releases:
          - Release process: 'docs/release-process.md'
          - Release notes: 'scripts/release-notes/README.md'
        - Setting up continuous integration: 'docs/ci.md'
        - Open source contribution: 'docs/os-contribution.md'
  - Extending / Overriding BLT: 'docs/extending-blt.md'
  - Contributing: 'CONTRIBUTING.md'
